// ==UserScript==
// @name         魔电官网文档中文化脚本
// @description  汉化了官网文档中的神符之语、装备等内容
// @copyright    2019 黑本
// @version      0.4.0
// @author       黑本
// @license      MIT
// @homepageURL  https://space.bilibili.com/12221554
// @match        https://docs.median-xl.com/doc/*
// @downloadURL      https://raw.githubusercontent.com/hibem/MedianXLDocCN/master/Lang_CN.js
// @updateURL      https://raw.githubusercontent.com/hibem/MedianXLDocCN/master/Lang_CN.js
// @run-at       document-end
// @grant        none
// ==/UserScript==
(function() {
    'use strict';

    document.body.innerHTML = document.body.innerHTML
//合成公式
    .replace(/Far from being the interesting magical gimmick you may be used to, the Median XL cube is a powerful weapon of war./g, '跟原版里无足轻重的公式不同，赫拉迪克宝箱在魔电里起到了极为重要的作用。')
    .replace(/These reagents can be found by killing the appropriate monster:/g, '获取方式')
    .replace(/Catalyst of Disenchantment: kill the Smith on Normal difficulty/g, '分解催化剂 Catalyst of Disenchantment：普通难度下消灭铁匠（A1 军营）')
    .replace(/Catalyst of Learning: kill Izual on Nightmare difficulty/g, '学习催化剂 Catalyst of Learning：噩梦难度下消灭衣卒尔（A4 绝望平原）')
    .replace(/>Oils</g, '>油剂 Oils<')
    .replace(/These reagents can be bought from a vendor in each town, except Oil of Conjuration which must be found./g, '每一关的有特定商人出售：<br>Act1 基德 Gheed<br>Act2 卓格南 Drognan<br>Act3 艾柯 Alkor<br>Act4 哈尔布Halbu<br>Act5 拉祖克 Larzuk')
    .replace(/>Arcane Shards</g, '>奥术碎片 Arcane Shards<')
    .replace(/This reagent is obtained by disenchanting unique items./g, '由分解暗金装备获取')
    .replace(/>Arcane Crystal</g, '>奥术水晶 Arcane Crystal<')
    .replace(/This reagent is created by cubing Arcane Shards in sets of five./g, '由奥术碎片X5合成')
    .replace(/>Arcane Cluster</g, '>奥术簇群 Arcane Cluster<')
    .replace(/This reagent is created by cubing an Arcane Crystal with an Oil of Craft./g, '由奥术水晶加锻造油合成（用于堆叠大量奥术水晶）')
    .replace(/>Mystic Orbs</g, '>通灵宝珠（神秘之球） Mystic Orbs<')
    .replace(/These reagents can be bought from any magic items vendor. Note that the strongest Mystic Orbs are not for sale.../g, '仍由上面的特定商人处出售，每颗15000，用于和装备合成，提升属性。<br>每合成1颗，装备需求等级+4，每件物品同一神秘之球最多合成5颗（通常叫做一组，增加需求等级20）。')
    .replace(/>Shrines</g, '>圣坛 Shrines<')
    .replace(/Orange crucifixes that drop in late Nightmare and in Hell difficulty. They enable you to create and bless items, see below./g, '噩梦后期开始掉落，用于制作圣坛手工装备')
    .replace(/>Mark of Infusion</g, '>注入标记 Mark of Infusion<')
    .replace(/This reagent is obtained by killing Shenk, the Overseer on any difficulty./g, '消灭任意难度的督军山克（Act5 第一个小站往回走）')
    .replace(/DISASSEMBLE ITEMS INTO RESOURCES/g, '将无用的装备分解成战略物资')
    .replace(/Arcane Shards, Crystals and Clusters/g, '奥术碎片/水晶和簇群 Arcane Shards, Crystals and Clusters')
    .replace(/Destroy up to 10 spare unique items to create Arcane Shards and combine those into Arcane Crystals, which are required for other cube recipes./g, '')
    .replace(/Any unique item \+ Catalyst of Disenchantment \→ Arcane Shards \+ Catalyst of Disenchantment/g, '暗金装备 + 分解催化剂 → 奥术碎片 + 分解催化剂（一次最多放10件装备）')
    .replace(/Arcane Shards x5 \→ Arcane Crystal/g, '奥术碎片 x5 → 奥术水晶')
    .replace(/You can also create an Arcane Cluster for easier Arcane Crystal safekeeping/g, '使用下列公式制造奥术簇群来储存大量的奥术水晶')
    .replace(/Arcane Crystal \+ Oil of Craft \→ Arcane Cluster/g, '奥术水晶 + 锻造油 → 奥术簇群（1）</div></p><p><div class="reagent" style="max-width: 750px">奥术簇群（n） + 奥术水晶 x X → 奥术簇群（n + X）</div></p>')
    .replace(/>Signets of Learning</g, '>学识图章 Signets of Learning<')
    .replace(/Destroy up to 25 spare sacred unique or set items to create Signets of Learning. Click the signet to gain 1 attribute point permanently./g, '分解神圣暗金或者套装装备来获得学识图章，一次最多放25件<br>右击学识图章可以得到永久的额外属性点。')
    .replace(/Any sacred unique\/set item \+ Catalyst of Learning \→ Signet of Learning \+ Catalyst of Learning/g, '神圣 暗金/套装 物品 + 学习催化剂 → 学识图章 + 学习催化剂')
    .replace(/Each character can use a maximum of 400 Signets of Learning./g, '每个角色通过学识图章获得的额外属性点最多为400。')
    .replace(/>ITEM QUALITY RECIPES/g, '装备品质更改公式')
    .replace(/CHANGE THE QUALITY LEVEL OF YOUR ITEMS/g, '')
    .replace(/Upgrade to Non-magical Item/g, '非魔法装备（白色/灰色带孔）')
    .replace(/Upgrade any item to regular quality or a regular item to superior. This also rerolls the socket count on the item./g,
             '重置任何品质装备为非魔法装备，并随机打孔（0 - 最大），用于制作神符之语底材以及利用A1铁匠任务奖励升级黄金。')
    .replace(/Low quality weapon\/armor \+ Oil of Enhancement \→ reroll item as regular/g, '低品质 武器/护具 + 强化油 → 重置物品为 普通')
    .replace(/Any quality weapon\/armor \+ Oil of Renewal \→ reroll item as superior/g, '任意品质 武器/护具 + 翻新油 → 重置物品为 超强')
    .replace(/Upgrade to Magical Item/g, '魔法物品（蓝色）')
    .replace(/Upgrade a plain superior item \(white or grey\) to a basic magical item./g, '')
    .replace(/Superior weapon\/armor \+ Oil of Enhancement \→ reroll item as magic/g, '白/灰 武器/护具 + 强化油 → 升级物品为 魔法物品')
    .replace(/Reroll Magic to Honorific/g, '荣耀物品（绿色）')
    .replace(/Honorific items are blank items that receive a double bonus from Mystic Orbs. This enables you to create your own custom items from scratch, provided you have some money to spend on the ingredients and the Mystic Orbs./g,
        '')
    .replace(/Magic weapon\/armor \+ Mark of Infusion \→ return item as honorific/g, '蓝色武器/护具 + 注入标记 → 升级物品为 荣耀物品')
    .replace(/Honorific items have no modifiers, but have maximum sockets and receive a double bonus from Mystic Orbs./g,
             '荣耀物品是一件没有词缀的装备，它强大的地方在于可以获得通灵珠宝的双倍加成和对应装备品阶的最大孔数。')
    .replace(/Reroll any Item to Unique/g, '暗金装备')
    .replace(/This powerful recipe uses the reagents obtained by disenchanting other uniques to turn any tiered item of your choosing into a unique. But choose wisely, because the crystals are precious and costly to replace./g,
             '暗金装备属性词条拥有变量，可以通过多次重置来达到最佳变量，建议用在使用周期最长的品阶4物品上。')
    .replace(/Any non-sacred item \+ Oil of Enhancement \+ Arcane Crystal x2 \→ reroll item as unique/g, '任意非神圣物品 + 强化油 + 奥术水晶 x2 → 重置物品为暗金')
    .replace(/Reroll Modifiers/g, '属性重置')
    .replace(/These recipes reroll the properties and socket count on any superior item. This is useful to try and get better the superior bonuses on your item before making a runeword./g,
             '该公式重置超强物品（白/灰）的词条属性和孔数。<br>通过反复使用该公式，达到想要的ED数值/最大孔/0孔，配合成功应用幸运油，真香，啪，真贵！<br>用于制作强大的神符之语底材。')
    .replace(/Superior item \+ Oil of Renewal \→ reroll item/g, '超强的 武器/护具 + 翻新油 → 刷新属性')
    .replace(/This recipe keeps the item level the same - unless it's over 99, in which case it reduces it to 99./g, '该公式保持原有物品等级（iLv），但是iLv超过99级的话会降低到99。')
    .replace(/Rare Downlevel/g, '黄金物品降级')
    .replace(/This recipe allows you to create yourself some baseline items. These items can be helpful to craft low-level items with space for Mystic Orbs./g,
             '初期时为物品降级，为通灵珠宝留下更多等级空间，用途不大。')
    .replace(/Rare weapon\/armor \+ rare amulet \+ rare ring \→ reroll item as level 1 rare item/g,
             '黄金武器/护具 + 黄金项链 + 黄金戒指 → 重置物品等级为 1')
    .replace(/UPTIER RECIPE/g, '品级升级公式')
    .replace(/UPGRADE ITEMS TO THE NEXT HIGHER TIER/g, '提升装备品级至更高一阶')
    .replace(/item tiers./g, '装备品级。')
    .replace(/Uptiering an item increases its base statistics and maximum sockets but also increases requirements. These recipes cannot create Sacred items./g,
             '提升装备的品阶和最大孔数，同时装备穿戴需求也会增加。这个公式无法创造神圣物品')
    .replace(/This recipe works for tiered items of all qualities. If the item is unique, its stats will be upgraded to match the next tier on the/g,
             '该公式作用于所有品级装备，包括暗金，在暗金装备升阶时，各条属性同样会得到提升，可以参考')
    .replace(/\<\/a> page./g, '</a> 这个页面。')
    .replace(/Non-sacred weapon\/armor \+ Arcane Crystal \→ reroll as next higher tier/g, '任意非神圣 武器/护具 + 奥术水晶 → 品级升阶')
    .replace(/AFFIX RECIPES/g, '物品词条配方')
    .replace(/ENHANCE YOUR ITEMS WITH EXTRA MAGICAL BONUSES/g, '给装备添加大量魔法属性')
    .replace(/Mystic Orbs add a magical bonus to an item at the cost of a higher required level to use the item. There are many known types sold by vendors, but rumours persist of lost ancient orbs with miraculous powers.../g,
             '商人处出售的通灵宝珠可以增加装备的固定属性，代价是提升的装备的等级需求，另外世界还会掉落一些商人处无法购买的强大宝珠。')
    .replace(/Any equippable item \+ regular Mystic Orb \→ add orb bonus and \+4 required level/g,
             '任意可装备物品 + 通灵宝珠 → 装备附加宝珠词条且需求等级+4')
    .replace(/You can only apply up to 5 of the same type of regular Mystic Orb to your item./g, '同一属性宝珠在一件装备上最多可以使用 5 次。')
    .replace(/The level requirement penalty is applied after taking into account both the base item required level and the level of any socket fillers. /g,
             '通灵宝珠对装备的等级提升是基于装备的需求的等级，包括镶嵌物。<br>')
    .replace(/This means for example if you have a belt with required level 20, add five orbs \(level penalty \+20\) and socket a Rha rune \(required level 100\), you get a belt with required level 100\+20 \= 120. /g,
             '举个例子，你的腰带等级需求是20，然后MO了5颗通灵宝珠（等级要求增加20），然后又镶嵌了一枚Rha符文（需要等级100），那么腰带的等级要求为 100 + 20 = 120级。<br>')
    .replace(/For that reason, to avoid going over required level 140 on accident, always add the socket fillers before adding orbs./g,
             '这就意味着，你在MO装备时得计算好镶嵌之后的等级。')
    .replace(/Socket Punch/g, '打孔公式')
    .replace(/Use this recipe to add extra sockets to an item. The more jewels you feed this recipe, the more sockets it will create./g, '')
    .replace(/Non-socketed item \+ jewel x\[1-6\] \→ returns item with \[1-6\] sockets/g,
             '无孔装备 + 珠宝 [ 1 - 6 ] → 装备 [ 1 - 6 孔 ]')
    .replace(/>Warning! </g, '>警告！ <')
    .replace(/This recipe will not go over the max natural sockets an item can have. Lower tier items have a lower socket count. Excess jewels are wasted. You also cannot add more sockets to an item that already has some./g,
             '装备根据类型和品级，最大孔数不同，投入超出最大孔数的珠宝，并不能打出更多的孔，并且多出的珠宝不会返还。<br>你无法在已经有孔的装备上使用这个公式。')
    .replace(/>Lucky Bonus/g, ' id="luckyb">幸运加成')
    .replace(/This recipe grants one chance to add a minor extra bonus to an item. Any item that has been transmuted with this recipe will show up as/g,
             '该公式可以为装备增加一个额外的词条。<br>任何使用过该公式的装备会增加一个')
    .replace(/ class\=\"brightgreen\"\>Already upgraded\!\</g, ' style="color:#02c109;"> 已升级！<')
    .replace(/. Items marked as such cannot be used for this recipe./g, '的词条，被标记的装备无法再次使用同类升级公式。')
    .replace(/Any item \+ Oil of Luck \→ returns item, may add bonuses/g, '任意装备 + 幸运油 → 装备附加词条')
    .replace(/This recipe has 20% chance to add any of the following bonuses:/g, '该公式只有20%的成功几率，附加词条如下：')
    .replace(/Magical Bonus/g, '魔法加成')
    .replace(/In some of the more powerful areas, you might find the Oil of Conjuration, which is a concoction highly sought after by many mages. Any item that has been transmuted with this recipe will show up as/g,
             '在一些危险的区域，你会发现一种戏法之油 Oil of Conjuration，它是法师们的最爱。<br>任何使用过该公式的装备会增加一个')
    .replace(/Any weapon \+ Oil of Conjuration \→ returns item, may add bonus/g, '任意武器 + 戏法之油 → 装备附加词条')
    .replace(/This recipe has 40% chance to add the following bonus:/g, '该公式只有40%的成功几率，附加词条如下：')
    .replace(/Adventurers say they have heard of powerful evil monsters creating these in locations such as the Icy Cellar, Abaddon, Pit of Acheron and Infernal Pit./g,
             '危险区域：Icy Cellar（冰窖）, Abaddon（阿巴顿）, Pit of Acheron（阿切尔龙穴） 和 Infernal Pit（炼狱洞穴）。')
    .replace(/Lottery Bonus/g, '超级加成')
    .replace(/This recipe works exactly like the lucky upgrade one, but it has only a 5% chance of adding the bonus. Any item that has been transmuted with this recipe will show up as/g,
             '跟上面两个公式一样，不过它更加强大，更加难得,需要与BOSS掉落的护符合成。<br>任何使用过该公式的装备会增加一个')
    .replace(/Any Unique\/Set Weapon \+ Legacy of Blood/g, '暗金或套装武器 + 血之遗产')
    .replace(/Any Unique\/Set Armor \+ Idol of Vanity/g, '暗金或套装护甲 + 虚荣雕像')
    .replace(/Any Unique Amulet \+ Moon of the Spider/g, '暗金项链 + 蜘蛛之月')
    .replace(/Any Unique Ring \+ Spirit Trance Herb/g, '暗金戒指 + 灵魂出窍药草')
    .replace(/Any Unique Quiver \+ Azmodan's Heart/g, '暗金箭袋 + 阿兹莫丹之心')
    .replace(/Any Unique Jewel \+ Sunstone of the Gods/g, '暗金珠宝 + 诸神的太阳石')
    .replace(/returns item, may add bonuses/g, '装备附加词条')
    .replace(/This recipe has 5% chance to add any of the following bonuses:/g, '该公式只有5%的成功几率，附加词条如下：')
    .replace(/SHRINES AND CRAFTING/g, '圣坛和手工')
    .replace(/CALL ON DIVINE FORCES TO CRAFT YOUR OWN ITEMS/g, '为自己创造独一无二的物品')
    .replace(/In Nightmare and Hell difficulty, you may find blessed relics from the ancient labyrinth beneath Tristram, stolen before its collapse./g,
             '')
    .replace(/During those dark days the holy shrines in the cathedral's catacombs offered salvation to some adventurers and damnation to others; removed from their sockets, the enchanted crosses cannot permanently affect humans anymore, but their divine powers can/g,
             '')
    .replace(/be applied to items./g, '')
    .replace(/There are 16 types of shrines with eldritch names. Beware, results may vary depending on divine will./g, '总共有16种不同的圣坛，它们提供了不同的属性加成')
    .replace(/The following shrines exist:/g, '圣坛列表：')
	.replace(/Abandoned Shrine/g, '废弃圣坛 Abandoned Shrine ')
	.replace(/Creepy Shrine/g, '惊悚圣坛 Creepy Shrine')
	.replace(/Eerie Shrine/g, '可怖圣坛 Eerie Shrine')
	.replace(/Enchanted Shrine/g, '强化圣坛 Enchanted Shrine')
	.replace(/Fascinating Shrine/g, '迷人圣坛 Fascinating Shrine')
	.replace(/Hidden Shrine/g, '隐藏圣坛 Hidden Shrine')
	.replace(/Intimidating Shrine/g, '威吓圣坛 Intimidating Shrine')
	.replace(/Magical Shrine/g, '魔法圣坛 Magical Shrine')
	.replace(/Ornate Shrine/g, '华丽圣坛 Ornate Shrine')
	.replace(/Quiet Shrine/g, '静谧圣坛 Quiet Shrine')
	.replace(/Sacred Shrine/g, '神圣圣坛 Sacred Shrine')
	.replace(/Shimmering Shrine/g, '微光圣坛 Shimmering Shrine')
	.replace(/Spiritual Shrine/g, '精神圣坛 Spiritual Shrine')
	.replace(/Tainted Shrine/g, '污秽圣坛 Tainted Shrine')
	.replace(/Trinity Shrine/g, '三位一体圣坛 Trinity Shrine')
	.replace(/Weird Shrine/g, '怪异圣坛 Weird Shrine')
    .replace(/Each shrine comes with 10 charges. Each use in the cube will drain one charge. When you use up the last charge, it disappears./g,
             '每个圣坛掉落时都有10点能量，每次合成消耗一点，消耗完毕时，该圣坛便会消失。')
    .replace(/Experiment, learn and create some of the most powerful items in all of Sanctuary./g, '')
    .replace(/Shrine Vessels/g, '圣坛容器')
    .replace(/Carrying many holy relics can be a burden. Store your full shrines into a corresponding holy vessel that can hold up to 1000 shrines:/g,
             '使用下列公式将相同容器堆叠，以免占用太多仓库容量，最高堆叠上限：1000')
    .replace(/Shrine \(10\) \+ Oil of Craft \→ Shrine Vessel/g, '圣坛（10）+ 锻造油 → 圣坛容器')
    .replace(/Shrine Vessel \+ any amount of Shrines \(10\) \→ Shrine Vessel \(adds shrines\)/g, '圣坛容器（n） + 圣坛（10）x X → 圣坛容器（n + X）')
    .replace(/Shrine Vessel \→ Shrine Vessel \(-1\) \+ Shrine/g, '圣坛容器（ X ） → 圣坛容器（X - 1）+ 圣坛（10）')
    .replace(/Shrine Crafting/g, '圣坛手工')
    .replace(/Use a shrine to turn any sacred item into a powerful crafted item. The crafted item comes with several random rare modifiers and additional preset modifiers based on shrine type. The preset modifiers may stack with the rare modifiers, creating some very powerful items./g,
             '使用圣坛创造的手工物品，拥有随机添加的词条（基于物品iLv）和圣坛固定的词条加成，因为随机的性质，它可能会变得非常强大。')
    .replace(/Rare\/Crafted Sacred item \+ Shrine \→ reroll item as crafted \+ Shrine \(-1 charge\)/g,
        '黄金/手工 神圣装备 + 圣坛（n） → 重置手工装备属性 + 圣坛（n - 1）')
    .replace(/Crafted items always have maximum sockets./g, '手工装备拥有装备最大孔数。')
    .replace(/Shrine Blessing/g, '圣坛洗礼')
    .replace(/A variant of shrine crafting, this recipe allows you to impart the blessings of the shrine unto an existing sacred item. This adds to the item the same preset shrine modifiers as the shrine crafting recipe and also subtracts 1 charge. You can only use this recipe once per item, so choose your shrine wisely./g,
             '除了制作手工神圣物品，圣坛还可以给神圣物品祝福，将圣坛的固定词条添加到装备上，装备只能使用一次圣坛祝福。')
    .replace(/Rare\/Crafted\/Honorific Sacred item \+ Shrine \+ 2x Arcane Crystal \→ add shrine bonuses \+ Shrine \(-1 charge\)/g,
        '黄金/手工/荣耀 神圣装备 + 圣坛 + 奥术水晶 x2 → 装备增加圣坛词条 + 圣坛（次数 -1）')
    .replace(/JEWELCRAFTING/g, '手工珠宝')
    .replace(/CREATE YOUR OWN JEWELS/g, '')
    .replace(/Jewelcrafting/g, '')
    .replace(/You can craft jewels as well, for an even higher degree of customizing your items./g, '手工珠宝可以通过符文增加固定词条，从而更好的定制你的装备属性。<br>')
    .replace(/The crafted jewel comes with a few random rare modifiers and always gets all preset modifiers based on the used rune./g, '除了符文带来的固定词条外，还会增加随机词条，这将可能造就非常鬼酷的属性。<br>')
    .replace(/The preset modifiers may stack with the rare modifiers, creating some very powerful jewels./g, '不像圣坛装备，做手工珠宝使用的符文不会被消耗掉，另外，镶嵌前别忘了使用对它使用<a href="#luckyb">幸运油</a>。')
    .replace(/Jewel \+ Rune \+ Oil of Craft \+ Arcane Crystal\/Shards \→/g, '珠宝 + 符文 + 锻造油 + 奥术碎片/水晶 →')
    .replace(/Rune \+ Arcane Shards \(-1\) \+ Crafted Jewel with added bonuses/g, '符文 + 奥术碎片（-1）+ 手工珠宝')
    .replace(/Every time you craft a Jewel, its item level is reduced by 5%, rounded up and capped at 1 and 99./g, '每洗一次属性,珠宝的iLv会降低 5%，由于词条和iLv有关，所以洗几次没有好属性，就可以换珠宝了。')
    .replace(/The preset modifiers on the jewel depend on the rune used, as follows:/g, '符文带来的固定词条属性如下：')
    .replace(/MISCELLANEOUS RECIPES/g, '其他配方')
    .replace(/EVERYTHING ELSE/g, '')
    .replace(/Gem Upgrade/g, '宝石升级')
    .replace(/You can upgrade gems to the higher quality levels. Note that unlike classic Diablo II, this recipe only requires two gems, not three./g,
             '你可以将宝石升级到更高一级。跟原版不一样的是，只需要两颗相同等级的即可升级，而不用三颗。')
    .replace(/Same gem x2 \→ next higher gem quality/g, '相同宝石 x2 → 更高一级的宝石')
    .replace(/Rune Upgrade\/Downgrade/g, '符文升级和降级')
    .replace(/You can upgrade or downgrade runes to the next higher or lower rune. This is useful when you need a certain exact rune to create a runeword./g,
             '符文可以升级和降级,这个公式便于你得到你需要的。')
    .replace(/Same rune x2 \→ rune one level higher/g, '相同的符文 x2 → 符文升级')
    .replace(/Same rune x4 \→ rune two levels higher/g, '相同的符文 x4 → 符文升2级')
    .replace(/Same rune x2 \+ rune one level higher \→ rune two levels higher/g, '相同的符文 x2 + 更高一级的符文 → 符文升2级')
    .replace(/Rune \→ rune one level lower/g, '符文 → 符文降级')
    .replace(/These recipes do not allow you to obtain or downgrade:/g, '你无法将此配方应用于下列符文上（超过50号）：')
    .replace(/Great Runes/g, '超强符文')
    .replace(/Elemental Runes/g, '元素符文')
    .replace(/Unsocket Recipe/g, '取出镶嵌物')
    .replace(/These recipes separate the socket fillers \(gems, jewels, runes\) from an item and return both the item and the socket fillers./g,
             '该公式允许玩家取出装备中的镶嵌物（珠宝、宝石和符文），并保留装备。')
    .replace(/Magical, Rare, Set, Unique, Crafted or Honorific:/g, '魔法，黄金，套装，暗金，手工或者荣耀装备：')
    .replace(/Socketed item \+ Oil of Disjunction \→ separate item and socket fillers/g, '已镶嵌装备 + 分离油 → 未镶嵌装备 + 镶嵌物')
    .replace(/Non-magical:/g, '灰色装备：')
    .replace(/Socketed item \+ Oil of Disjunction \+ perfect gem x3 \→ separate item and socket fillers/g, '已镶嵌装备 + 分离油 → 未镶嵌装备 + 镶嵌物')
    .replace(/Non-magical socketed items are grey, and therefore include runewords. The price is higher for these items to prevent unhealthy amounts of runeword rerolling./g,
             '灰色物品通常用于神符之语，所以增加了宝石需求，使重置神符之语变量的难度提高。')
    .replace(/R.I.P. Recipe/g, 'R.I.P. 配方（杀死怪物恢复平静）')
    .replace(/If you went wild with reanimate items and now you can\'t see the forest for the reanimated Ents, this recipe can help. It adds the \'R.I.P.\' modifier to an item, causing your kills to stay dead instead of rising up to get in your way. This should help out players with slower computers./g,
             '使用该公式，将不会复生任何怪物，关爱老旧电脑，人人有责。')
    .replace(/Any item \+ Oil of Renewal \+ Arcane Crystal \→ returns item with R.I.P. modifier/g,
             '任意装备 + 翻新油 + 奥术水晶 → 装备增加 R.I.P.词条')
    .replace(/This recipe adds the following bonus:/g, 'R.I.P.词条的含义是：')
    .replace(/Slain Monsters Rest in Peace/g, '杀死怪物恢复平静（超度尸体，无法使用复生、尸爆等技能）')
    .replace(/Do not forget the Arcane Crystal or you will destroy more than you bargained for./g, '<span style="color:red;">千万别忘了放奥术水晶，否则你会直接将装备重置为非魔法（引起舒适）</span>。')
    .replace(/Cow Level Portal/g, '秘密奶牛关卡')
    .replace(/Moo! You need to stand in the Rogue Encampment in Hell difficulty to use this recipe. Be careful, the cows have been beefed up compared to the regular Diablo II./g,
             '哞哞哞！在地狱难度下的罗格营地使用该配方。<br>注意！这里的牛都经过了强化。')
    .replace(/Wirt's Leg \→ Cow Level portal/g, '维特之腿 → 奶牛关红门')
    .replace(/Killing the Cow King does not disable this recipe./g, '奶牛之王随便杀，不影响你开门。')
    .replace(/Want to show the common rabble in your game how rich and powerful you are\? This recipe consumes some of the rarest trophies in the game and returns a completely useless item that grants you a glowing red aura. Show it to friends and strangers so they know that you are strong, powerful and wealthy enough to waste trophies on a worthless item./g,
             '这个公式消耗了几件极难获得的奖杯来制造一个没有任何属性的物品，带着这件物品会使你发出红色的光芒，去别人的房间里展示吧，你这个超级肝帝！')
    .replace(/See the Uberquests section for more information./g, '')
    .replace(/Archbishop Lazarus Trophy \+ Kabraxis Trophy \+ Uldyssian Trophy \+ Vial of Elder Blood \→ I Am Rich Gem/g,
             '大主教拉扎鲁斯的奖杯 + 卡布拉西斯的奖杯 + 乌迪贤的奖杯 + 长老之血 → 我他妈贼有钱之石')
    .replace(/I Am Rich/g, '马云公式')
    .replace(/This recipe is inspired by the \$1000 iPhone application that does nothing./g, '灵感来源于价值1000美元屁用都没的APP。')


//任务
    //等级挑战
    .replace(/After killing the Infernal Contraption in Normal difficulty, enter the portal to access Tran Athulua, here begins Level Challenge 1./g, '普通难度下杀死炼狱装置（Act 5 巴尔前最后一波怪），开启红门后进入阿苏拉城（妹子岛 伪）。 ')
    .replace(/Find and defeat the three Priestesses. Each will drop a shard of her respective element./g, '找到并杀死三个祭司，分别会掉落火焰、冰冷和闪电碎片。')
    .replace(/Cube all three shards below level 60 to create the Sunstone./g, '将三枚元素碎片合成得到太阳石（60级以内）')
    .replace(/Sunstone of the Twin Seas/g, 'Sunstone of the Twin Seas<br>双子海的太阳石')
    .replace(/Although the level can be accessed at level 45, you cannot cube the shards together until at least level 50./g, '该场景最低进入等级为45级，但合成需要等级为50级。')
    .replace(/If you are past level 59, you can still do the challenge, but with the added penalty of 2 Arcane Crystals per 10 levels./g, '<br>如果你已经超过了59级，虽然可以继续挑战并合成，但每超过10级，合成时就需要花费额外2枚奥术水晶。')
    //恩奈德挑战
    .replace(/MINIMUM LEVEL 80/g, '挑战需要等级 80')
    .replace(/Access this challenge through killing Mephisto in Nightmare Difficulty, and kill an Ennead Necromancer boss to obtain a/g, '噩梦难度下杀死 Act3 Boss 墨菲斯托，开启红门后进入库拉斯特3000BA（k3k 伪），杀死任意一个恩奈德死灵法师（分别在地图中3个边缘处）会掉落一个')
    .replace(/Heroic Torch/g, '英雄火炬')
    .replace(/Place this torch in the Horadric Cube and transmute to receive your class charm./g, '将火炬单独合成，将得到你的角色护身符')
    .replace(/Your class charm adds the following bonuses depending on your class:/g, '各职业角色护符属性如下：')
    .replace(/Unlocks your Ennead Skill/g, '解锁你的恩奈德技能')
    .replace(/Your free bonus skill/g, '解锁你的新技能')
    .replace(/Keep in Inventory to Gain Bonus/g, '护符 - 放入背包生效')
    .replace(/<\/u>: uses /g, '专属<\/u>: ')
    .replace(/Sacred Sunstone/g, '神圣太阳石 Sacred Sunstone')
    .replace(/Shadow Vortex/g, '暗影涡流 Shadow Vortex')
    .replace(/Worldstone Orb/g, '世界之石之球 Worldstone Orb')
    .replace(/Caoi Dulra Fruit/g, '草杜拉的水果 Caoi Dulra Fruit')
    .replace(/Soulstone Shard/g, '灵魂石碎片 Soulstone Shard')
    .replace(/Eye of Divinity/g, '圣力之眼 Eye of Divinity')
    .replace(/Nexus Crystal/g, '枢纽水晶 Nexus Crystal')
    .replace(/This skill can be found at the top right of your first skill tab. When you complete this uber, keep the charm in your inventory. This allows you to put skill points into the skill./g, '')
    .replace(/This skill can be found at the top left of your first skill tab. When you/g, '该技能位于技能书奖励标签的左上角。')
    .replace(/complete the Ennead Challenge and receive your class charm and keep it in your/g, '完成挑战并将得到的角色护符放在背包内，')
    .replace(/inventory. This allows you to put skill points into the skill./g, '即可解锁技能。')
    .replace(/Ennead Challenge/g, '恩奈德挑战')
    .replace(/SPELLBIND/g, '法术缠绕<br>Spellbind')
    .replace(/The basilisk snake of Skartara is a devious creature whose bite turns flesh to stone. A skilled amazon warrior may carry a few to the battlefield in a leather bag for an unexpected surprise./g, '诅咒 - 扔出使敌人石化的蛇群')
    .replace(/Effect: throws snakes that turn enemies to stone/g, '--- 你们都是石头人，不许说话不许动。')
    .replace(/PRISMATIC CLOAK/g, '棱镜斗篷<br>Prismatic Cloak')
    .replace(/Dancing on the edge of shadow and playing with the light allows the assassin to weave a protective magical cloak./g, '被动 - 获得魔法和物理伤害抵抗（Flat Mr/Dr），并且给天赋技能浴血提供部分抵抗效果')
    .replace(/physical damage/g, 'physical Damage')
    .replace(/Passive effect: increases magical and physical Damage reduction, and provides similar bonuses to Bloodbath/g, '--- 出自黑暗，匿于光明，你们谁都看不见我。')
    .replace(/Passive effect: avoids damage/g, 'Passive effect: avoids Damage')
    .replace(/IMMORTAL/g, '不朽<br>Immortal')
    .replace(/Passive effect: avoids Damage when standing still and improves hit recovery/g, '--- 来啊，正面刚啊，谁动谁就是孙子。')
    .replace(/Running away is for the weak. A barbarian warrior who runs is easy prey. One who stands his ground in the face/g, '被动 - 当你站着不动的时候，获得更高的闪避和击中回复')
    .replace(/of death may survive, for he is the one the ancestral spirits will favour./g, '')
    .replace(/LIFESHIELD/g, '生命之盾<br>Lifeshield')
    .replace(/The fruits of the Glor-An-Fhaidha, the mystical tree of life, can bring back mortals from the brink of/g, '被动 - 增加大量的生命值和防御')
    .replace(/death. Aside from their healing effect on humans and other animals, the juice of the Glor-An-Fhaidha's/g, '')
    .replace(/fruits can be applied to armour, making it as hard as the bark of a thousand year tree./g, '')
    .replace(/Passive effect: provides a bonus to maximum life and defense/g, '--- 安静的做一棵大树。')
    .replace(/BLACK MASS/g, '黑色物质<br>black Mass')
    .replace(/The dragon god of death Trag’Oul takes his faithful under his wings, turning aside blades and arrows./g, '效果 - 引导型技能，按住不动以保护自己和召唤物')
    .replace(/This powerful spell requires total concentration and is easily broken when the caster is disturbed./g, '')
    .replace(/Effect: press and hold to protect self and nearby minions/g, '--- 对，谁动谁就是孙子！')
    .replace(/DIVINE APPARITION/g, '神圣显现<br>Divine Apparition')
    .replace(/Like a deus ex machina, the paladin of Zakarum descends upon the battlefield, his mere appearance chilling his/g, '效果 - 瞬移并冻结目标附近怪物')
    .replace(/heathen enemies to the bone./g, '')
    .replace(/Effect: teleport to target location and freeze enemies/g, '--- 我没动，我用的瞬移。')
    .replace(/SYMBOL OF ESU/g, '艾苏的符号<br>Symbol of Esu')
    .replace(/The symbol of the ancient witch queen is a specially crafted conductive adamantine moon crescent that/g, '效果 - 使用红蓝药合成的月牙符号，在使用时立即恢复')
    .replace(/accumulates ambient energy from the magic in the environment, releasing it as a healing pulse when broken./g, '')
    .replace(/Effect: create a symbol in the cube that instantly heals life and mana/g, '--- 吃块饼干看楼上的傻子们。')
    .replace(/Reward:/g, '奖励：')
    .replace(/Level Challenge /g, '等级挑战')
    .replace(/MINIMUM LEVEL 45/g, '挑战需要等级 45')
    .replace(/Veteran Tokens/g, '角色护符的提升')
    .replace(/In </g, '在<')
    .replace(/Nightmare and Hell/g, '噩梦和地狱')
    .replace(/ difficulties, you can find <b>veteran monsters<\/b> near the end of each Act. There/g, '难度，你能在每关靠近关底的随机地点寻找到一种名字是绿色的怪物，每关一种，一共5种。')
    .replace(/are 5 types of veteran monsters, one for each Act./g, '')
    .replace(/Kill them and receive an 'Evil Eye' token./g, '杀死它们以获得它们的眼球。')
    .replace(/Veterans/g, '它们分别是')
    .replace(/Clawstorm Terror/g, 'Act1 - 利爪风暴（会释放知识旋风（毒） 监牢第一层至关底）')
    .replace(/Fairy Witch/g, 'Act2 - 精灵巫师（会释放从天而降的火雨 推荐刷术士峡谷）')
    .replace(/Glowing Blob/g, 'Act3 - 光斑（技能印象不深 推荐刷崔凡克）')
    .replace(/Landmass/g, 'Act4 - 地皮（攻击扇形范围 火焰之河至关底）')
    .replace(/Bane Hunter/g, 'Act5 - 灾厄猎人（小黑豹 亚瑞特巅峰杀完3爹进门后搜寻至关底）')
    .replace(/\[Class Charm\] \+ each of the 5 tokens → returns \[Class Charm\] with added bonuses/g, '角色护符 + 5种不同的眼球 → 角色护符升级版')
    .replace(/This upgrade recipe adds the following bonuses:/g, '升级后会增加下列属性：')
    .replace(/to \[Your class\] Skill Levels/g, '[你的职业]技能等级')
//Boss战
    .replace(/chance to drop a trophy on Hell difficulty. Cube the trophy with the charm for a small bonus./g, '的机会掉落一个奖杯，使用奖杯和该护符合成以得到额外的属性。')
    .replace(/Maximum Skill Level Increased by/g, '技能等级上限提高')
    .replace(/Horror Under Tristram/g, '崔斯特姆地下的恐惧')
    .replace(/Butcher's Lair \(Act 1: Tristram\)/g, '屠夫的巢穴 ( Act1 ➤ 石块旷野 ➤ 崔斯特瑞姆 ➤ 西北角的屋子内，无红门，鼠标移动到屋子内可见入口 )')
    .replace(/A bloated and grotesque creature, the Butcher was a sadistic being that relished in the torture and pain of others. It hunted endlessly for fresh meat. /g, '')
    .replace(/Although retellings of the Darkening of Tristram describe how the Butcher was defeated deep within the Labyrinth, the horrific culling of the city in recent times, following the Dark Wanderer's wake, seems to have stirred this malevolent spirit back to evil once more./g, '略')
    .replace(/The Butcher is a strong melee fighter. His tainted cleaver hits hard and just like in the Tristram Cathedral, he will hunt you down./g, '屠夫是一个强大的狂战士，使用他的杀猪刀摧毁面前的一切事物。')
    .replace(/Upon striking you or a minion, he has a chance to incite a Bloodlust which fuels Sacrificial Shrines into emitting heavily damaging shockwaves./g, '屠夫每次击中都有机会给四周的祭坛充能，被充能的祭坛则会射出一道破坏性的冲击波。')
    .replace(/And to boot, he also is considerably tanky./g, '充能成功时，屠夫也会变的更硬。')
    .replace(/Defeat the Butcher on Hell difficulty to get/g, '击败屠夫可获得')
    .replace(/The Butcher's Tooth<\/span>.<\/p>/g, '屠夫的牙齿</span>.</p>')
    .replace(/The Butcher's Tooth/g, '屠夫的牙齿<br>The Butcher\'s Tooth')
    .replace(/>Infernal Machine/g, '>炼狱生成器')
    .replace(/Infernal Cave \(Act 1: The Pit\)/g, '狱火洞穴  ( Act1 ➤ 泰摩高地 ➤ 洞穴 ➤ 狱火洞穴 )')
    .replace(/Who knew the fallen clans were technologically adept\? This rickety contraption contains wooden clockwork/g, '')
    .replace(/mechanisms and the necessary runes to open a gateway to any location in the Burning Hells and protect/g, '')
    .replace(/itself against any attackers. This enables it to summon hellish creatures at a rapid rate and strike/g, '')
    .replace(/enemies down with powerful rune magic upon being attacked. Move quickly, because time is against you./g, '略')
    .replace(/The tower summons a selection of dangerous elite monsters. Try to reach it as quickly as possible, avoiding/g, '这家伙会不停召唤精英级别的怪物，你必须快速接近并杀死它。')
    .replace(/or teleporting past elites. Beware the elites with a slowing attack: Marbled Frog and Basilisk/g, '小心那些带控制的怪物：绿蛤蟆、BUG蛇和突脸人马，还有伤害巨高的大型化身火球怪。')
    .replace(/Defeat the Infernal Machine on Hell difficulty to get the/g, '击败炼狱生成器可获得')
    .replace(/Optical Detector<\/span>.<\/p>/g, '光学检测器</span>.</p>')
    .replace(/Optical Detector/g, '光学检测器<br>Optical Detector')
    .replace(/>Death Projector/g, '>死亡发射器')
    .replace(/The Proving Grounds \(Swampy Pit - Flayer Jungle\)/g, '试验场 (Act3 ➤ 剥皮丛林 ➤ 沼泽地洞 ➤ 试验场)')
    .replace(/The Swampy Pit serves as testing grounds for Mephisto\'s latest siege weapon. The Death Projector/g, '')
    .replace(/slowly rotates, firing a devastating energy beam in a full circle, annihilating anything in its path./g, '略')
    .replace(/The siege tower is tended to by trained Zakarumite techpriests. Its magitech shield is impenetrable/g, '由一群专业萨卡兰姆技术人员维护的机器，会顺时针发射毁灭性的射线。')
    .replace(/to all weapons, but when it senses a Mechanic nearby, it lowers its shield to enable maintenance. In/g, '机器本身免疫武器伤害，但是当技术人员在附近时，它会卸下护盾以便于维护。')
    .replace(/this state, the Death Projector can be damaged, though its fortified outer shell still harmlessly deflects/g, '')
    .replace(/a percentage of all incoming attacks. The Mechanics themselves carry portable gap generators and are/g, '')
    .replace(/impossible to hit or kill. Damage the Death Projector while avoiding Mechanics until the devilish device/g, '这帮技工随身携带了光学偏转装置，使得他们无法被选中。')
    .replace(/finally falls./g, '<br>绕圈躲避死亡射线，保持萨卡兰姆在机器附近，然后利用你的输出技能在躲避伤害的同时对机器造成伤害。')
    .replace(/Defeat the Death Projector on Hell difficulty to get the/g, '击败死亡发射器可获得')
    .replace(/Laser Focus Crystal<\/span>.<\/p>/g, '激光对焦水晶</span>.</p>')
    .replace(/Laser Focus Crystal/g, '激光对焦水晶<br>Laser Focus Crystal')
    .replace(/>Assault on Mount Arreat/g, '>亚瑞特圣峰之战')
    .replace(/Arreat Summit \(Act 5: Arreat Summit\)/g, 'Act5 ➤ 远古之路 ➤ 亚瑞特山脉之巅')
    .replace(/In ages past, Diablo himself attempted to invade Mount Arreat to destroy the Worldstone and was repelled/g, '')
    .replace(/by the Bear tribe defenders and their king, the shaman Koth. This is a reenaction of that battle/g, '')
    .replace(/on the peak of Mount Arreat, with you as Diablo./g, '略')
    .replace(/Kill Narthal to open a portal to the old Arreat Summit./g, '杀死3爹的守卫 那骚儿（Narthal）开启红门去回顾那一场远古的战役')
    .replace(/The Bear Shamans wield the Hawk Talons ability, a trap which releases axes, the ability to cast a Guard Tower, as well as throwing axes at the player. Thanks to their connection to the primal forces, all shamans have an innate 50% resistance to all. /g, '玩家扮演迪亚波罗进攻亚瑞特圣峰，圣峰的野蛮人守卫们拥有50%的伤害免疫，并会投掷让人僵直的斧头，召唤箭塔陷阱。')
    .replace(/King Koth, on the other hand who wields dual swords, can also cast Hawk Talons, but instead of Guard Tower, he casts Fortress./g, '科什大王手持双剑，还会施放堡垒陷阱。')
    .replace(/In many aspects this is the physical version of the Tal Rasha fight./g, '<br>避免陷入不断的僵直，并快速的清理附近的野蛮人守卫后，与科什大王战斗。')
    .replace(/Defeat King Koth on Hell difficulty to get the/g, '击败科什大王可获得')
    .replace(/Sacred Worldstone Key<\/span>.<\/p>/g, '神圣世界之石钥匙</span>.</p>')
    .replace(/Sacred Worldstone Key/g, '神圣世界之石钥匙<br>Sacred Worldstone Key')
    .replace(/>The Binding of Baal/g, '>巴尔的束缚')
    .replace(/Act 2: Tal Rasha's Tomb/g, 'Act2 ➤ 都瑞尔的房间外')
    .replace(/Kill Zoltun Kulle to open a Portal to the old Canyon of the Magi./g, '杀死佐顿库勒开启红门去回顾塔拉夏与巴尔的战斗')
    .replace(/Reenact the capture and imprisonment of Baal by Tal Rasha and his Horadrim, with you playing the/g, '')
    .replace(/role of Baal. To protect their leader, the Horadrim weave warding spells that make Tal Rasha immortal/g, '')
    .replace(/until the last of his soldiers has died and their spirits have faded./g, '略')
    .replace(/During this uberquest, you morph into Baal when you are near Tal Rasha. The archmage himself is immune/g, '玩家扮演巴尔与塔拉夏率领的赫拉蒂姆法师们战斗。')
    .replace(/to all damage until you get rid of all Horadric Mages. Even then, Tal Rasha has a phasing spell that/g, '古老的法师们会施放闪电和火焰法术，并拥有50%的伤害免疫，')
    .replace(/negates a percentage of incoming attacks and their elemental affinity grants all mages 50% resistance/g, '当赫拉蒂姆法师存在时，塔拉夏处于无敌状态。')
    .replace(/to all. Being magical in nature, the shield aura is vulnerable to resistance breaking spells, offering/g, '杀死所有的法师，然后再去刚塔拉夏。')
    .replace(/the hero another way to deal with Tal Rasha. Beware the Horadrim's fire and lightning spells, empowered/g, '')
    .replace(/with ancient metamagic to bypass up to 30% of your resistances, Tal Rasha able to bypass 40%./g, '')
    .replace(/Defeat Tal Rasha on Hell difficulty to get the/g, '击败塔拉夏可获得')
    .replace(/Scroll of Kings<\/span>.<\/p>/g, '王者卷轴</span>.</p>')
    .replace(/Scroll of Kings/g, '王者卷轴<br>Scroll of Kings')
    .replace(/4>Akarat/g, '4>阿卡拉特')
    .replace(/<br>Torajan Jungles/g, '<br>托拉然丛林（Act3 ➤ 营地内东南方铁匠下面红门 ➤ 托拉然丛林）')
    .replace(/Akarat the Prophet is the name of the ascetic who founded the religion and customs of the Zakarum Church. /g, '')
    .replace(/It is said that he did so after the visit of Archangel Yaerius in his dreams. Moved by what he\'d seen, Akarat set out/g, '')
    .replace(/on a grand journey to the cities of Kehjistan, intent on enlightening his fellow men about the divine Light he claimed/g, '')
    .replace(/existed within everyone. However the prophet\'s legacy is clouded with uncertainties and it is said that one day he simply/g, '')
    .replace(/disappeared in the jungles of Kehjistan. While his teachings had left their mark, they would flounder in obscurity for a millennium./g, '略')
    .replace(/The corrupted spirit of Akarat is protected by heavenly invulnerability and is impossible to attack/g, '')
    .replace(/directly. Remember that a religion is nothing without followers, therefore strike down his surrounding apostles first./g, '')
    .replace(/The death of one of his apostles unleashes a wave of holy energy, reducing all resistances of other/g, '')
    .replace(/apostles to -100% and breaking the immunity shield of Akarat himself, reducing all resistances to/g, '')
    .replace(/0% for a few precious seconds. This does however enrage them and they will attack you with renewed/g, '')
    .replace(/vigour. Killing an apostle may be difficult due to the mass healing spell they cast when low on health,/g, '')
    .replace(/as well as the storm of magical hammers with which they pummel you from a distance and their ability/g, '')
    .replace(/to heal when they slay a minion or hero. Akarat himself is blessed in another way as well: the spirits of the/g, '')
    .replace(/Light repel a percentage of all incoming attacks./g, '在丛林的最东方，阿卡拉特带领他的信徒们驻扎于此，他有一个无敌BUFF，杀死他的白衣教众可以短暂的破除他的BUFF，你必须在几秒内杀死他，否则他会再次无敌并释放治疗法术快速恢复，如果伤害不够，可以试着雇佣Act 3的瘟疫法师协助你完成这个任务。')
    .replace(/Defeat Akarat on Hell difficulty to get the/g, '击败阿卡拉特可获得')
    .replace(/Visions of Akarat<\/span>.<\/p>/g, '阿卡拉特的视界</span>.</p>')
    .replace(/Visions of Akarat/g, '阿卡拉特的视界<br>Visions of Akarat<br>（奖杯：增加最大生命和法力值 5%）')
    .replace(/4>Lord Aldric Jitan/g, '4>领主艾德瑞克·吉坦')
    .replace(/Driven mad by nightmares, the Western aristocrat Lord Aldric Jitan hopes to summon a terrible demon/g, '')
    .replace(/and plunge the land into darkness. Stop him before he succeeds./g, '略')
    .replace(/The demonic powers guiding his actions imbue him and his guardsmen/g, '')
    .replace(/with 50% all resistances and the ability to harmlessly deflect a percentage of incoming attacks./g, '')
    .replace(/The guardsmen are tougher than anything that came before and will heal themselves, inflict tri-elemental/g, '')
    .replace(/damage and summon guard towers that will pummel the living daylights out of you if you stand still/g, '')
    .replace(/for too long. Keep moving and the towers will vanish behind you./g, '在丛林的中上位置，领主吉坦带着一群流浪的佣兵驻扎于此，这些敌人会施放箭塔技能，无数的箭塔可以造成巨量伤害，你可以选择逐步清理过去或者通过走位将小兵甩在身后，只是需要耗费一些时间。')
    .replace(/Defeat Lord Aldric Jitan on Hell difficulty to get the/g, '击败吉坦领主可获得')
    .replace(/Moon of the Spider<\/span>.<\/p>/g, '蜘蛛之月</span>.</p>')
    .replace(/Moon of the Spider/g, '蜘蛛之月<br>Moon of the Spider<br>（奖杯：增强武器伤害 25%）')
    .replace(/4>Horazon\'s Sanctum/g, '4>霍拉松的圣所')
    .replace(/Dimensional Sanctum \(Act 3: Caldeum\)/g, '次元圣殿 (Act 3 ➤ 库拉斯特下层门口杀死狗头怪头目 Vizier ➤ 红门进卡尔蒂姆(记得点开小站) ➤ 次元圣殿(东南角))')
    .replace(/Horazon the Summoner, in his arcane sanctuary, summoned a mighty demon lord imbued by a power so strong that it was quickly able to overwhelm the sorcerer. /g, '')
    .replace(/Horazon, unable to defeat the demon without paying with his life, managed to trap the creature in the farthest reach of his sanctuary and split off the prison zone from the rest of the structure banishing it under the earth where it now sits in a containment dimension. Breaking in and defeating the demon may yield great rewards./g, '略')
    .replace(/Kill the Vizier in the Lower Kurast entrance and open a Portal to Caldeum/g, '')
    .replace(/Heed the familiar\'s holographic warning. The Creature of Flame, although not very strong on its own, has the ability to open/g, '')
    .replace(/Dimensional Rifts, summoning demons from the depths of hell. If unprepared, the player can become overwhelmed./g, '')
    .replace(/Not only can it open rifts, but can defend itself with a mortar attack and Lava Pit./g, '霍拉松在此地囚禁了一只火焰生物（冒着白色雾气的BOSS）,挺简单的，就是跑来跑去有点烦，另外还会施放次元之门召唤精英怪物，没什么提示，干就完了。')
    .replace(/Defeat the Creature of Flame on Hell difficulty to get/g, '击败火焰生物可获得')
    .replace(/Horazon\'s Focus<\/span>.<\/p>/g, '霍拉松的瞩目</span>.</p>')
    .replace(/Horazon\'s Focus/g, '霍拉松的瞩目<br>Horazon\'s Focus')
    .replace(/4>Black Road/g, '4>黑暗之路')
    .replace(/Church of Dien-Ap-Sten \(Act 1: Bramwell - Rogue Encampment\)/g, '迪纳普斯登教堂 (Act 1 ➤ 瓦瑞夫旁边大车进布兰威尔 ➤ 迪纳普斯登教堂 Church of Dien-Ap-Sten)')
    .replace(/The now former acolyte of the Zakarum-priesthood Buyard Cholik, facing the limits of his own mortality, slowly/g, '')
    .replace(/started despising the so called \"Religion of the Light\", regretting all the years he faithfully devoted to the Zakarum/g, '')
    .replace(/order which was now exposing all of its frailty while confronting the wicked intents and machinations of the Lord of Hatred/g, '')
    .replace(/himself.  Buyard Cholik, fueled by an evergrowing thirst for knowledge related to the pursuit of eternal life, eventually,/g, '')
    .replace(/came to know about the powerful and mighty demon Kabraxis. Inebriated by the promise of immortality, the former Zakarum/g, '')
    .replace(/priest joined forced with Kabraxis the Thief of Hope, becoming an anchor for the banished demon between his prison realm/g, '')
    .replace(/and the mortal plane. Thus Buyard Cholik started preparing Sanctuary for the demon's coming establishing a new cult/g, '')
    .replace(/dedicated to the prophet Dien-Ap-Sten, Kabraxis in disguise, wearing the new title of \"Wayfinder\" for his followers/g, '')
    .replace(/and creating the first church of the Way of Dreams in the ancient city of Bramwell, from where he plan to extend/g, '')
    .replace(/his foul influence on the whole region./g, '略')
    .replace(/Buyard is a primarily fire based caster whose Ultimate skill is the ability to summon a horde of possessed cultists to swarm you. /g, '')
    .replace(/To damage Buyard, he must be in the fire circle in the middle of his room, but beware of one of his attacks that makes that circle treacherous to enter./g, '邪恶主教拜耶德.邱力克会使用火焰法术和召唤邪教徒，只有在房间中央的火圈内他才会受到伤害。')
    .replace(/Killing Buyard Cholik gives you/g, '击败拜耶德.邱力克可获得')
    .replace(/The Black Road<\/span> /g, '《黑暗之路》</span>')
    .replace(/charm which allows you to unlock your Black Road skill./g, '，这个护符解锁了你的黑暗之路技能（技能树奖励页面右上角技能）')
    .replace(/The Black Road/g, '《黑暗之路》<br>The Black Road')
    .replace(/Unlocks your Black Road Skill/g, '解锁黑暗之路技能')
    .replace(/\+150 Life/g, '+150 生命')
    .replace(/\+150 Mana/g, '+150 法力')
    .replace(/4>Legacy of Blood/g, '4>血之遗产')
    .replace(/Chamber of Blood \(Torajan Jungles\)/g, ' (Act3 ➤ 托拉然丛林小站 ➤ 往西走，位于丛林中下部 ➤ 鲜血之厅（入口是个地窖）)')
    .replace(/Bartuc, the Warlord of Blood, was once Horazon\'s brother in the Vizjerei mage clan. Whereas Horazon/g, '')
    .replace(/wanted to summon demons to enslave them, Bartuc chose to worship them and traded his soul for demonic/g, '')
    .replace(/power. Their conflict eventually led to a civil war that shattered the mage clan. Although Bartuc/g, '')
    .replace(/was eventually destroyed by the very powers he sought to control, his soul and power have been claimed/g, '')
    .replace(/by the forces of Hell. It may be possible to find Bartuc\'s spirit in the crypt where his cursed/g, '')
    .replace(/armour was buried.../g, '略')
    .replace(/Bartuc and his summoned Blood Golems have ranged attacks and can hurt a lot in this tiny room. Protected/g, '')
    .replace(/by the power of his cursed armour, Bartuc and his golems are invulnerable to damage. However, his/g, '')
    .replace(/Wychwind blade throw requires him to concentrate on the spell and drop his resistances for a brief/g, '')
    .replace(/time, and his dimwitted golems may briefly forget to shield themselves when they successfully hit/g, '')
    .replace(/you and are distracted by your suffering./g, '在这个狭小的空间内，巴图克和他召唤的鲜血石磨们会对你输出巨量伤害，通常他们是无敌的，但在击中你时会偶尔进入忘我状态从而暴露弱点，在巴图克非无敌状态时迅速杀死他，不然死的就是你，注意，进入房间20秒后就会锁定关卡，如果你死了，需要建立新的游戏才能再次进入。')
    .replace(/Defeat Bartuc on Hell difficulty to get the/g, '击败巴图克可获得')
    .replace(/Legacy of Blood<\/span>.<\/p>/g, '血之遗产</span>.</p>')
    .replace(/Legacy of Blood/g, '血之遗产<br>Legacy of Blood<br>（奖杯：角色整体防御增加 15%）')
    .replace(/4>Bull Prince Rodeo/g, '4>公牛王子罗迪欧')
    .replace(/Corral of Corruption \(The Secret Cow Level\)/g, ' 腐化牛栏(秘密奶牛关卡 ➤ 击杀母牛王掉落另一条腿 ➤ 在奶牛关中将腿合成)')
    .replace(/Defeat Bull Prince Rodeo on Hell difficulty to get the/g, '击败罗迪欧可获得')
    .replace(/Fool\'s Gold<\/span>.<\/p>/g, '愚者金币</span>.</p>')
    .replace(/Fool\'s Gold/g, '愚者金币<br>Fool\'s Gold')
    .replace(/The moolicious heir to the Cow King\'s throne, Bull Prince Rodeo is out to exact his indiscriminate/g, '')
    .replace(/revenge for all the cattle killed by humans./g, '略')
    .replace(/Rodeo is very aggressive and has a stunning Hoof Stomp and the Blink spell, making it difficult to put/g, '')
    .replace(/some distance between you and him. He can also summon more cows or call upon a Stampeding Herd of exploding/g, '')
    .replace(/cows that ploughs across the screen, trampling all in their path. This ability is unblockable, unresistable/g, '')
    .replace(/and will destroy you if you don\'t get out of the way in time. But his most common spell, in cooperation/g, '')
    .replace(/with another victim of cruel farming practices, is a wave of chickens that will pursue their victim relentlessly,/g, '')
    .replace(/inflicting devastating hurt with their beaks if they connect. The chickens can be dodged by staying mobile./g, '这个罗迪欧王子的牛栏，真是一个鸡飞狗跳可以形容，他自身会瞬移骑脸砍，施放全体击退僵直的冲击波，四处飞啄的鸡，犁过全屏的爆炸牛群。<br>好在他这个地方死了还可以再进来，那就说一个需要注意的地方，请在牛场红门旁边用另一只腿开启腐化牛栏的红门，这样你挂了后可更快的回来。')
    .replace(/Killing Rodeo does <b>not<\/b> prevent you from entering the Cow Level again./g, '击杀母牛王和罗迪欧不会影响你开启秘密奶牛关的红门。')
    .replace(/4>Rathma Square/g, '4>拉斯玛广场')
    .replace(/Act 3: Caldeum/g, ' (Act3 ➤ 卡尔蒂姆 ➤ 拉斯玛广场（小站北面）)')
    .replace(/On Hell difficulty, Primus drops the/g, '击败普莱姆斯可获得')
    .replace(/Spirit Trance Herb<\/span>.<\/p>/g, '灵魂出窍药草</span>.</p>')
    .replace(/Spirit Trance Herb/g, '灵魂出窍药草<br>Spirit Trance Herb<br>（奖杯：10% 不间断攻击（UA））')
    .replace(/Back in the days when Kurast was the centre of civilisation and black magic was not yet frowned upon,/g, '')
    .replace(/this was where the priests of Rathma - the necromancers - practiced their art. The place was abandoned/g, '')
    .replace(/when the religion of Zakarum took over the city and banned pagan magic, making it the perfect hiding/g, '')
    .replace(/place for an ancient evil bent on taking out the Church from within. Primus, son of Mephisto, was the/g, '')
    .replace(/leader of the Cult of the Triune in ages past before its destruction. His efforts to rebuild the Triune/g, '')
    .replace(/were shut down by the crusaders of Zakarum, but he remains a formidable foe, doubly so in the home city/g, '')
    .replace(/of the Zakarum./g, '略')
    .replace(/Primus himself is not particularly hard, despite his powerful ranged Bladestorm attack. The blades track/g, '')
    .replace(/your position, but do less damage than his normal attack and can be avoided, blocked and dodged. His/g, '')
    .replace(/guard dogs are the real challenge. After several millennia in and around Rathma Square, his Gore Crawlers/g, '')
    .replace(/can raise themselves from the dead. Shattering the corpse does not stop this, but the resurrection takes/g, '')
    .replace(/10 seconds, during which you can attempt to run away and ditch them./g, '首先说一下，这个地图不锁定，BOSS普莱姆斯不回血，可以拖尸体过。<br>真正恐怖的不是BOSS，而是大量的爬行者，这些爬行者死后会点亮一个火把，10秒后原地复活，杀死怪物回复平静或者毁掉他们的尸体都无法阻止他们复活，所以你一定要快，快速的找到普莱姆斯，杀死他，捡起战利品，退出，否则你将被狗群淹没。')

    .replace(/4>The Veiled Prophet/g, '4>蒙面先知')
    .replace(/Cathedral of Vanity \(Library of Fate\)/g, ' ( Act4 ➤ 绝望平原击杀衣卒尔开启金刚大门 ➤ 银城（记得点亮小站） ➤ 命运图书馆 ➤ 虚荣大教堂 )')
    .replace(/Defeat Inarius on Hell difficulty to get the/g, '击败伊纳瑞斯可获得')
    .replace(/Idol of Vanity<\/span>.<\/p>/g, '虚荣雕像</span>.</p>')
    .replace(/Idol of Vanity/g, '虚荣雕像<br>Idol of Vanity<br>（奖杯：+10% 召唤物生命和伤害）')
    .replace(/According to religious myth, the mortal plane Sanctuary was created by the fallen angel Inarius and/g, '')
    .replace(/the demon Lilith to serve as a refuge from the Eternal War. The two created a race of servants from the/g, '')
    .replace(/earth which were to worship them for all eternity. However, humanity broke free from its shackles when/g, '')
    .replace(/a small group of farmers rediscovered their birthright and ancient powers inherited from their supernatural/g, '')
    .replace(/parents. As the edyrem army grew, Inarius descended into megalomanic madness and was eventually destroyed/g, '')
    .replace(/along with his golden cathedral of vanity. It is whispered that the ghosts of Inarius and his closest/g, '')
    .replace(/worshippers still roam the cathedral./g, '略')
    .replace(/The Crystal Ball is the last of the cathedral\'s magical defences. The tower exudes a holy invulnerability/g, '')
    .replace(/shield to protect nearby revelers and casts searing beams of angelic lightning that destroys anything/g, '')
    .replace(/it touches. Destroy the Crystal Ball to dispel the immortality from the other enemies./g, '')
    .replace(/4>Heart of Sin/g, '4>罪恶之心')
    .replace(/Realm of Sin \(Act 4: Chaos Sanctuary\)/g, ' (Act4 ➤ 混沌避难所 ➤ 击杀冈姆掉落钥匙 ➤ 右键点击钥匙打开通向罪恶之境的红门)')
    .replace(/Kill Ghom to obtain a Key of Sin, right click it to open a portal to the Realm of Sin./g, '')
    .replace(/The Lord of Sin walks the earth. In his weakened state, he hides in the catacombs of Kurast, where his mere presence turned the surrounding area into a hellish landscape, feasting/g, '')
    .replace(/on the dark rituals of Mephisto\'s chosen. Destroy him before he becomes a threat./g, '略')
    .replace(/Azmodan is accompanied by a legion of Balrogs that cast Fire Fountain and Ravening Beasts which unleash molten boulders./g, '')
    .replace(/High maximum fire resistance will help against these threats, but not as much as against Azmodan himself. /g, '')
    .replace(/Though he uses Flamestrike, it is very strong even against high fire resistance. And as for an attack that\'s not fire damage based, he will cast Fortress/g, '')
    .replace(/which can subdue his ranged attackers. Movement here is key./g, '远离阿兹莫丹施放的堡垒，随时注意地面标记，他施放的烈焰一击足以秒杀任何人，附近还潜伏着隐形的火球怪，躲避他们的伤害，使用你的最强技能回城是最好的方法。')
    .replace(/Defeat Azmodan on Hell difficulty to get/g, '击败阿兹莫丹可获得')
    .replace(/Azmodan\'s Heart<\/span>.<\/p>/g, '阿兹莫丹之心</span>.</p>')
    .replace(/Azmodan\'s Heart/g, '阿兹莫丹之心<br>Azmodan\'s Heart<br>（奖杯：+150 生命和法力）')




    //亚马逊
    .replace(/SUN STRIKE/g, 'SUNSTRIKe<br>炎阳击')
    .replace(/Effect: shoots a piercing fire arrow that leaves a trail behind/g, '投射物 - 射出一只可穿透的火箭并留下火焰')
    .replace(/BARRAGE/g, 'BARRAGe<br>弹幕')
    .replace(/Effect: shoots arrows in random directions/g, '投射物 - 密集箭矢的旋转射击')
    .replace(/PHALANX/g, 'PHALANx<br>方阵')
    .replace(/Effect: summons a line of spirit archers/g, '投射物 - 召唤一排弓箭手射向下方')
    .replace(/DRAGONLORE/g, 'DRAGONLORe<br>巨龙传说')
    .replace(/Passive devotion effect: adds elemental damage and magic damage if you have elemental and magic items/g, '被动 - 强化你的冰火电伤害')


    //技能
    .replace(/ to Divine Apparition/g, 'Divine Apparition（神圣显现 -瞬移，冰冻）')
    .replace(/ Mark of the Wild/g, 'Mark of the Wild（野性印记 -增伤）')
    .replace(/ to Hamstring/g, 'Hamstring（断筋 -近战、晕眩）')
    .replace(/ to Mana Sweep/g, 'Mana Sweep（法力扫荡 -吸法、伤害）')
    .replace(/ to Mana Tide Totem/g, 'Mana Tide Totem（法力潮汐图腾）')
    .replace(/ Bloodlust/g, 'Bloodlust（嗜血 -增伤）')
    .replace(/ Banish/g, 'Banish（放逐，诅咒 -减敌最大生命）')
    .replace(/ Frog Prince/g, 'Frog Prince（青蛙王子 -施放冰环）')
    .replace(/ to Plague/g, 'Plague（疫病）')
    .replace(/ Shower of Rocks/g, 'Shower of Rocks（石头澡 -伤害、减速）')
    .replace(/ Spike Nova/g, 'Spike Nova（飞矛新星 -伤害）')
    .replace(/ to Wyrd/g, 'Wyrd（环形冲击波）')
    .replace(/ to Iron Spiral/g, 'Iron Spiral（铁螺旋）')
    .replace(/ to Winter Avatar/g, 'Winter Avatar（凛冬化身 -冰环）')
    .replace(/ Ice Lance/g, 'Ice Lance（冰枪）')
    .replace(/ to Deathgaze/g, 'Deathgaze（死亡凝视）')
    .replace(/ Glacial Nova/g, 'Glacial Nova（冰川新星）')
    .replace(/ Lifeblood/g, 'Lifeblood（命脉 -生命回复）')
    .replace(/ Gamma Field/g, 'Gamma Field（毒伤）')
    .replace(/ to Dragon Wyrms/g, 'Dragon Wyrms（翼龙 -陷阱）')
    .replace(/ to Noctule/g, 'Noctule（山蝠 -近战）')
    .replace(/ Apocalypse/g, 'Apocalypse（天启 -火伤）')
    .replace(/ to Hammertime/g, 'Hammertime（锤子时间）')
    .replace(/ Nightmare/g, 'Nightmare（噩梦 -诅咒，减速）')
    .replace(/ to Wild and Free/g, 'Wild and Free（自由自在，被动加防）')
    .replace(/ Shatterblade/g, 'Shatterblade（刀片）')
    .replace(/ Punisher/g, 'Punisher（惩罚者）')
    .replace(/ Charged Strike/g, 'Charged Strike（充能一击）')
    .replace(/ Squall Wave/g, 'Squall Wave（飓风波）')
    .replace(/ Blade Spirits/g, 'Blade Spirits（刀刃之灵 -召唤）')
    .replace(/ Shuriken Flurry/g, 'Shuriken Flurry（手里剑乱舞）')
    .replace(/ Fire Splash/g, 'Fire Splash（火花飞溅）')
    .replace(/ Venomous Spirit/g, 'Venomous Spirit（剧毒之灵 -法术）')
    .replace(/ Abyss/g, 'Abyss（深渊 -法师冰法术）')
    .replace(/ Frozen Crown/g, 'Frozen Crown（冰冻王冠 -法术）')
    .replace(/ to Vanquish/g, 'Vanquish（征服 -3秒增伤BUFF）')
    .replace(/ Flamefront/g, 'Flamefront（烈焰前线 -法术）')
    .replace(/ Crucify/g, 'Crucify（折磨 -近战）')
    .replace(/ Charm/g, 'Charm（魅惑）')
    .replace(/ Gift of Inner Fire/g, 'Gift of Inner Fire（内燃之礼 -群体回血）')
    .replace(/ Celerity/g, 'Celerity（迅捷 -加速）')
    .replace(/ Mind Flay/g, 'Mind Flay（精神鞭笞 -骑士法术）')
    .replace(/ Blink/g, 'Blink（闪烁 -瞬移，晕眩）')
    .replace(/ Arrow Swarm/g, 'Arrow Swarm（箭群 -多重射击）')
    .replace(/ Wraith Arrow/g, 'Wraith Arrow（幽灵箭 -箭术 ）')
    .replace(/ Frozen Soul/g, 'Frozen Soul（冰冻之魂）')
    .replace(/ Bloodspeaker's Mark/g, 'Bloodspeaker\'s Mark（鲜血议长的标记 -短时召唤）')
    .replace(/ to Tantrum/g, 'Tantrum（暴怒 -小范围的冲击）')
    .replace(/ Meteor Shower/g, 'Meteor Shower（陨石雨 -大范围火伤）')
    .replace(/ Rune of Fire/g, 'Rune of Fire（火焰符文 -原地放置）')
    .replace(/ Rune of Ice/g, 'Rune of Ice（冰冻符文 -原地放置）')
    .replace(/ Doom/g, 'Doom（末日 -减抗诅咒）')
    .replace(/ Singularity/g, 'Singularity（奇点 -范围法术）')
    .replace(/ to Silver Dart/g, 'Silver Dart（银镖 -追踪穿透）')
    .replace(/ Thunderstone/g, 'Thunderstone（雷电石 -法术）')
    .replace(/ Cluster Bomb/g, 'Cluster Bomb（子母弹 -火伤陷进）')
    .replace(/ Terror Strike/g, 'Terror Strike（恐怖打击 -增益型近战）')
    .replace(/ Searing Glow/g, 'Searing Glow（灼热辉光）')
    .replace(/ Plague Avatar/g, 'Plague Avatar（瘟疫化身 -小范围持续毒伤）')
    .replace(/ to Amatoxin/g, 'Amatoxin（武器淬毒 -被动）')
    .replace(/ Countdown/g, 'Countdown（法术 -大范围冰伤）')
    .replace(/ Arachnomancy /g, 'Arachnomancy （蛛卜术 -毒伤）')
    .replace(/ Lightning Shield/g, 'Lightning Shield（闪电护盾）')
    .replace(/ Supernova/g, 'Supernova（超新星 -大范围电伤）')
    .replace(/ Lightning Wall/g, 'Lightning Wall（闪电墙 -晕眩）')
    .replace(/ Lionheart/g, 'Lionheart（狮心 -增益 丐版的龙之心）')
    .replace(/ to Bloodstar/g, 'Bloodstar（血星 -缓慢移动的火伤）')
    .replace(/ Rapture/g, 'Rapture（狂喜 -增益，加全速）')
    .replace(/ to Shatter the Flesh/g, 'Shatter the Flesh（撕碎血肉 -尸爆冷冻）')
    .replace(/ Rust Storm/g, 'Rust Storm（腐蚀风暴 -诅咒减防）')
    .replace(/ Cataclysm/g, ' Cataclysm（突变 -火球环形散射）')
    .replace(/ to Summon Avalanche/g, 'Summon Avalanche（召唤雪怪 -冰伤并增加召唤物法伤）')
    .replace(/ Forked Lightning/g, 'Forked Lightning（分叉闪电）')
    .replace(/ to Magic Missiles/g, ' Magic Missiles（魔法飞弹）')
    .replace(/ Parasite/g, 'Parasite（寄生虫 -近战弹射）')
    .replace(/ Kraken Stance/g, 'Kraken Stance（海妖姿态 -增加冰火电伤）')
    .replace(/ Stampede/g, 'Stampede（涌动 -多重投掷）')
    .replace(/ Lorenado/g, 'Lorenado（知识旋风 -毒伤）')
    .replace(/ Fairy Ring/g, 'Fairy Ring（）')
    .replace(/ to Jitan’s Gate/g, 'Jitan’s Gate（吉坦之门 -瞬移）')



    //怪物
    .replace(/ Flesh Clan/g, 'Flesh Clan（羊头人战士）')
    .replace(/ Necrobot/g, 'Necrobot（死灵机器人）')
    .replace(/ Venom Fiend/g, 'Venom Fiend（毒魔）')
    .replace(/ Condemned/g, 'Condemned（火人）')
    .replace(/ Moon Knight/g, 'Moon Knight（月亮骑士）')
    .replace(/ Banshee/g, 'Banshee（女妖）')
    .replace(/ Acid Beast/g, 'Acid Beast（酸液兽）')
    .replace(/ Umbaru Spirit/g, 'Umbaru Spirit（部族巫师，特钢则）')
    .replace(/ Horror Arche/g, 'Horror Arche（恐怖射手）')
    .replace(/ Burning Dead Archer/g, 'Burning Dead Archer（燃烧射手）')
    .replace(/ Bone Archer/g, 'Bone Archer（骷髅射手）')
    .replace(/ Dark Templar/g, 'Dark Templar（黑暗圣堂）')
    .replace(/ Infernal Lord/g, 'Infernal Lord（炼狱领主）')
    .replace(/ Zombie/g, 'Zombie（僵尸）')

    //符文
    .replace(/El Rune/g, '1# El')
    .replace(/Eld Rune/g, '2# Eld')
    .replace(/Tir Rune/g, '3# Tir')
    .replace(/Nef Rune/g, '4# Nef')
    .replace(/Eth Rune/g, '5# Eth')
    .replace(/Ith Rune/g, '6# Ith')
    .replace(/Tal Rune/g, '7# Tal')
    .replace(/Ral Rune/g, '8# Ral')
    .replace(/Ort Rune/g, '9# Ort')
    .replace(/Thul Rune/g, '10# Thul')
    .replace(/Amn Rune/g, '11# Amn')
    .replace(/Sol Rune/g, '12# Sol')
    .replace(/Shael Rune/g, '13# Shael')
    .replace(/Dol Rune/g, '14# Dol')
    .replace(/Hel Rune/g, '15# Hel')
    .replace(/Io Rune/g, '16# Io')
    .replace(/Lum Rune/g, '17# Lum')
    .replace(/Ko Rune/g, '18# Ko')
    .replace(/Fal Rune/g, '19# Fal')
    .replace(/Lem Rune/g, '20# Lem')
    .replace(/Pul Rune/g, '21# Pul')
    .replace(/Um Rune/g, '22# Um')
    .replace(/Mal Rune/g, '23# Mal')
    .replace(/Ist Rune/g, '24# Ist')
    .replace(/Gul Rune/g, '25# Gul')
    .replace(/Vex Rune/g, '26# Vex')
    .replace(/Ohm Rune/g, '27# Ohm')
    .replace(/Lo Rune/g, '28# Lo')
    .replace(/Sur Rune/g, '29# Sur')
    .replace(/Ber Rune/g, '30# Ber')
    .replace(/Jah Rune/g, '31# Jah')
    .replace(/Cham Rune/g, '32# Cham')
    .replace(/Zod Rune/g, '33# Zod')
    .replace(/Sha Rune/g, '34# Sha')
    .replace(/Lah Rune/g, '35# Lah')
    .replace(/Kur Rune/g, '36# Kur')
    .replace(/Ix Rune/g, '37# Ix')
    .replace(/Thur Rune/g, '38# Thur')
    .replace(/Nas Rune/g, '39# Nas')
    .replace(/Ath Rune/g, '40# Ath')
    .replace(/Kra Rune/g, '41# Kra')
    .replace(/Vith Rune/g, '42# Vith')
    .replace(/No Rune/g, '43# No')
    .replace(/Yul Rune/g, '44# Yul')
    .replace(/Thai Rune/g, '45# Thai')
    .replace(/Rha Rune/g, '46# Rha')
    .replace(/Xar Rune/g, '47# Xar')
    .replace(/Nih Rune/g, '48# Nih')
    .replace(/Lai Rune/g, '49# Lai')
    .replace(/On Rune/g, '50# On')
    .replace(/Taha Rune/g, '51# Taha')
    .replace(/Ghal Rune/g, '52# Ghal')
    .replace(/Qor Rune/g, '53# Qor')
    .replace(/Krys Rune/g, '54# Krys')
    .replace(/Auhe Rune/g, '55# Auhe')
    .replace(/Shaad Rune/g, '56# Shaad')
    .replace(/Ma Rune/g, '魔法')
    .replace(/Po Rune/g, '毒素')
    .replace(/Fi Rune/g, '火焰')
    .replace(/Ea Rune/g, '大地')
    .replace(/Co Rune/g, '寒冰')
    .replace(/Li Rune/g, '闪电')
    .replace(/Xis Rune/g, '卡布')


//其他
    .replace(/Many runewords contain only one rune, but you can fill up the sockets /g, '许多神符之语仅需要一枚符文，但是你需要在镶嵌这枚符文')
    .replace(/before/g, '之前')
    .replace(/ the rune with jewels. To make a runeword in an item with 4 sockets, for example,/g, '用珠宝填满前面的孔，举个栗子，有一件装备有4个孔')
    .replace(/you must/g, '你必须按顺序')
    .replace(/ insert 3 jewels \+ 1 rune/g, '镶嵌 3枚珠宝和1枚符文')
    .replace(/Grey items only!/g, '只能用于灰色装备！')
    .replace(/Some people do not seem to know this. You can only make runewords in nonmagical socketed \(grey\) items!/g, '很多人看来不知道，你只能在普通带孔装备（灰色）上装备神符之语！')

    .replace(/ contains 537 all-new runewords./g, ' 包含了 537 个全新的神符之语')
    .replace(/LIST OF RUNEWORDS/g, '神符之语列表')
    .replace(/RUNEWORDS/g, '神符之语')
    .replace(/except /g, '除了 ')
    .replace(/Cannot be Unsocketed/g, '无法取出镶嵌物')


  //装备属性词条
    .replace(/Less Gold from Monsters/g, '减少金币掉落')
    .replace(/ Bonus Elemental Damage /g, ' 增加元素伤害')
    .replace(/Drains 2% Life per Second/g, '每秒流失2%的生命')
    .replace(/Amazing Grace/g, '奇异恩典')
    .replace(/ second Cooldown to Blade Spirits/g, ' 秒刀刃之灵冷却时间')
    .replace(/ over 2 seconds/g, '2秒内')
    .replace(/ Increased Mana Pulse Duration/g, ' 提升法力波动持续时间')
    .replace(/ Chance to cast level /g, ' 的机会施展等级 ')
    .replace(/ Hit Recovery/g, ' 快速打击恢复（FHR）')
    .replace(/ Block Speed/g, ' 格挡速度（FBR）')
    .replace(/ on Kill/g, ' 当杀死怪物')
    .replace(/ Enhanced Damage/g, ' 增强伤害（ED）')
    .replace(/ Enhanced damage/g, ' 增强伤害（ED）')
    .replace(/ Bonus to Attack Rating/g, ' 额外准确率（AR）')
    .replace(/ Bonus to All Attributes /g, ' 所有属性')
    .replace(/ to All Attributes/g, ' 所有属性')
    .replace(/ Gold Find/g, ' 更多金币')
    .replace(/ to Light Radius/g, ' 照亮范围')
    .replace(/ Bonus Damage to/g, ' 更多伤害')
    .replace(/ Increased Attack Speed/g, ' 增加攻速（IAS）')
    .replace(/ Attack Speed/g, ' 增加攻速（IAS）')
    .replace(/Adds /g, '增加 ')
    .replace(/ cold damage/g, ' 的冰冷伤害')
    .replace(/ poison damage/g, ' 的毒素伤害')
    .replace(/ fire damage/g, ' 的火焰伤害')
    .replace(/ lightning damage/g, ' 的闪电伤害')
    .replace(/ magic damage/g, ' 的魔法伤害')
    .replace(/ damage/g, ' 的伤害')
    .replace(/ to Maximum Damage/g, ' 最大伤害')
    .replace(/Based on Character Level/g, '基于角色等级')
    .replace(/ to all Attributes/g, ' 至所有属性')
    .replace(/ on Melee Attack/g, ' 当近战攻击时')
    .replace(/ to All Skills/g, ' 所有技能')
    .replace(/ to Minimum Damage/g, ' 最小伤害')
    .replace(/Stun Attack/g, '晕眩攻击')
    .replace(/ Bonus to Summoned Minion Life/g, ' 召唤物生命')
    .replace(/ to Summoned Minion Life/g, ' 召唤物生命')
    .replace(/ to Strength/g, ' 力量')
    .replace(/ Bonus to Energy Factor/g, ' 增加精力因子')
    .replace(/ to Energy/g, ' 精力')
    .replace(/ to Dexterity/g, ' 敏捷')
    .replace(/ Reanimate as/g, ' 复活为')
    .replace(/ Cast Speed/g, ' 快速施法（FCR）')
    .replace(/ Faster Cast Rate/g, ' 快速施法（FCR）')
    .replace(/ Life stolen per Hit/g, ' 生命偷取（LL）')
    .replace(/ Mana stolen per Hit/g, ' 法力偷取（LM）')
    .replace(/ to Life/g, ' 生命值')
    .replace(/Maximum Fire Resist /g, '最大火焰抗性 ')
    .replace(/Maximum Cold Resist /g, '最大冰冷抗性 ')
    .replace(/Maximum Lightning Resist /g, '最大闪电抗性 ')
    .replace(/Maximum Poison Resist /g, '最大毒素抗性 ')
    .replace(/Fire Resist /g, '火焰抗性（fr）')
    .replace(/Slow Target /g, '减慢目标')
    .replace(/Cold Resist /g, '冰冷抗性（cr）')
    .replace(/Lightning Resist /g, '闪电抗性（lr）')
    .replace(/Poison Resist /g, '毒素抗性（lr）')
    .replace(/Damage Reduced by /g, '物理抗性 ')
    .replace(/Physical Resist /g, '物理抗性 ')
    .replace(/Physical Damage Reduced by /g, '物理伤害降低（dr） ')
    .replace(/Elemental\/Magic Damage Reduced by /g, '元素/魔法伤害降低')
    .replace(/ to Poison Spell Damage/g, ' 至毒素法术伤害')
    .replace(/ to Lightning Spell Damage/g, ' 至闪电法术伤害')
    .replace(/ to Cold Spell Damage/g, ' 至冰冷法术伤害')
    .replace(/ to Fire Spell Damage/g, ' 至火焰法术伤害')
    .replace(/ to Physical\/Magic Spell Damage/g, ' 至物理/魔法伤害')
    .replace(/ Strength Factor to Spell Damage/g, ' 力量因子至法术伤害')
    .replace(/ Energy Factor to Spell Damage/g, ' 法力因子至法术伤害')
    .replace(/ to Spell Damage/g, ' 至所有法术伤害')
    .replace(/ Chance of Crushing Blow/g, ' 压碎性打击（CB）')
    .replace(/ Charges/g, ' 聚气')
    .replace(/ Combat Speeds/g, ' 所有战斗速度')
    .replace(/ Increased Healing Rate from Apples/g, '增加食用苹果的恢复效率')
    .replace(/ Chance of Uninterruptable Attack/g, ' 不间断攻击（UA）')
    .replace(/Total Character Defense Plus/g, '角色整体防御增加 ')
    .replace(/Total Character Defense /g, '角色整体防御 ')
    .replace(/ to Enemy Cold Resistance/g, ' 敌人冰冷抗性')
    .replace(/ to Enemy Poison Resistance/g, ' 敌人毒素抗性')
    .replace(/ to Enemy Fire Resistance/g, ' 敌人火焰抗性')
    .replace(/ to Enemy Lightning Resistance/g, ' 敌人冰冷抗性')
    .replace(/Increase Maximum Life and Mana /g, '增加最大生命和法力值 ')
    .replace(/Requirements /g, '需求 ')
    .replace(/ Damage to Demons/g, ' 对恶魔的伤害（DTD）')
    .replace(/ Life Regenerated per Second/g, ' 每秒生命恢复')
    .replace(/ Life on Striking/g, ' 击中时恢复生命')
    .replace(/ Mana on Striking/g, ' 击中时恢复法力')
    .replace(/ Life on Attack/g, ' 打击时恢复生命')
    .replace(/ Mana on Attack/g, ' 打击时恢复法力')
    .replace(/ Life after each Kill/g, ' 杀死怪物获取生命（LAEK）')
    .replace(/ Mana after each Kill/g, ' 杀死怪物获取法力（MAEK）')
    .replace(/Target Takes Additional Damage of /g, '目标受到额外伤害 ')
    .replace(/Indestructible/g, '无法破坏')
    .replace(/ Movement Speed/g, ' 移动速度')
    .replace(/ Magic Find/g, ' 魔法物品获取（MF）')
    .replace(/Enhanced Weapon Damage /g, '增强武器伤害 ')
    .replace(/ to Vitality/g, ' 体力')
    .replace(/Hit Causes Monster to Flee /g, '击中使怪物逃跑')
    .replace(/Attacker Flees after Striking /g, '受到打击时恐吓怪物')
    .replace(/Half Freeze Duration/g, '冰冻时间减半')
    .replace(/Cannot Be Frozen/g, '无法冰冻')
    .replace(/Maximum Mana /g, '增加法力值 ')
    .replace(/Maximum Life /g, '增加生命值 ')
    .replace(/Regenerate Mana /g, '法力恢复速度 ')
    .replace(/ Bonus to Buff\/Debuff\/Cold Skill Duration/g, '延长Buff/Debuff/冰冻技能的效果时间')
    .replace(/ Energy Factor to Spell Damage/g, ' 精力因子至法术伤害')
    .replace(/ to Enemy Elemental Resistances/g, ' 敌人元素抗性')
    .replace(/ to All Maximum Resistances/g, ' 最大元素抗性')
    .replace(/Maximum Elemental Resists/g, '最大元素抗性')
    .replace(/ to all vendor prices/g, ' 所有商品价格')
    .replace(/Elemental Resists /g, '元素抗性 ')
    .replace(/ Deadly Strike/g, ' 致命一击（DS）')
    .replace(/ to Summoned Minion Resistances/g, ' 召唤物抗性')
    .replace(/ Bonus to Summoned Minion Damage/g, ' 召唤物伤害')
    .replace(/ to Summoned Minion Damage/g, ' 召唤物伤害')
    .replace(/ to Summoned Minion Attack Rating/g, ' 召唤物准确率')
    .replace(/ to Maximum Barbarian Minions/g, ' 野蛮人召唤物数量')
    .replace(/ to Maximum Necromancer Minions/g, ' 死灵法师召唤物数量')
    .replace(/ Damage to Undead/g, ' 对不死生物的伤害（DTU）')
    .replace(/ Defense vs. Missile/g, ' 对飞弹的防御')
    .replace(/Ignore Target's Defense/g, '忽视目标防御')
    .replace(/ to Druid/g, ' 德鲁伊')
    .replace(/ to Assassin/g, ' 刺客')
    .replace(/ to Barbarian/g, ' 野蛮人')
    .replace(/ to Amazon/g, ' 亚马逊')
    .replace(/ to Sorceress/g, ' 法师')
    .replace(/ to Necromancer/g, ' 死灵法师')
    .replace(/ to Paladin/g, ' 圣骑士')
    .replace(/Amazon Only/g, '限亚马逊')
    .replace(/Druid Only/g, '限德鲁伊')
    .replace(/Assassin Only/g, '限刺客')
    .replace(/Barbarian Only/g, '限野蛮人')
    .replace(/Sorceress Only/g, '限法师')
    .replace(/Necromancer Only/g, '限死灵法师')
    .replace(/Paladin Only/g, '限圣骑士')
    .replace(/ over 1 seconds/g, '在1秒内')
    .replace(/ to Experience Gained/g, ' 经验获取')
    .replace(/ Life when Struck by an Enemy/g, '生命受打击时')
    .replace(/Mana when Struck by an Enemy/g, '法力受打击时')
    .replace(/ on Striking/g, ' 在打击时')
    .replace(/ when Struck/g, ' 受到打击时')
    .replace(/ when Attacked/g, ' 当击中时')
    .replace(/ on Death Blow/g, ' 当最后一击')
    .replace(/ when you Level-Up/g, ' 当升级时')
    .replace(/Slows Attacker by /g, ' 减慢攻击者 ')
    .replace(/Slows Ranged Attacker by /g, '减慢远程攻击者 ')
    .replace(/Slows Melee Target by /g, '减慢近战目标 ')
    .replace(/ Damage to The Zakarum/g, ' 对萨卡兰姆的伤害（DTZ）')
    .replace(/Attacker Takes Cold Damage of /g, '攻击者受到冰冷伤害 ')
    .replace(/Attacker Takes Fire Damage of /g, '攻击者受到火焰伤害')
    .replace(/ Bonus Elemental Damage to Bloodlust/g, ' 增加嗜血的元素伤害')
    .replace(/You may Only use Melee, Summon and Support Skills/g, '仅可使用近战，召唤和支援技能')
    .replace(/ Base Block Chance/g, ' 基础格挡值')
    .replace(/ Bonus to Poison Skill Duration/g, ' 增加毒素技能持续时间')
    .replace(/Poison Length Reduced by /g, ' 中毒时间减少 ')
    .replace(/Lion Stance Damage Bonus /g, ' 狮子姿态伤害增加 ')
    .replace(/ Slower Block Rate/g, ' 降低格挡速度')
    .replace(/Cold Absorb /g, ' 冰冷吸收')
    .replace(/Fire Absorb /g, ' 火焰吸收')
    .replace(/Lightning Absorb /g, ' 闪电吸收')
    .replace(/Poison Absorb /g, ' 毒素吸收')
    .replace(/ Fire Damage/g, ' 火焰伤害')
    .replace(/ Lightning Damage /g, ' 闪电伤害')
    .replace(/ Cold Damage /g, ' 冰冷伤害')
    .replace(/ Chance to Avoid Damage/g, ' 躲避伤害')
    .replace(/Druid Morph/g, '德鲁伊形态')
    .replace(/Based on Blessed Life Skill Level/g, '基于 Blessed Life 的等级')
    .replace(/ when using an Apple/g, ' 当食用苹果时')
    .replace(/ Damage Taken Goes To Mana/g, ' 受到伤害转化为法力')
    .replace(/Attacker Takes Elemental Damage of /g, '攻击者受到元素伤害 ')
    .replace(/One-Hand Damage/g, '单手伤害')
    .replace(/Two-Hand Damage/g, '双手伤害')
    .replace(/Throw Damage/g, '投掷伤害')
    .replace(/Required Level/g, '需要等级')
    .replace(/Required Strength/g, '需要力量')
    .replace(/Required Dexterity/g, '需要敏捷')
    .replace(/Strength Damage Bonus/g, '力量伤害加成')
    .replace(/Dexterity Damage Bonus/g, '敏捷伤害加成')
    .replace(/ per Strength/g, ' 每点力量')
    .replace(/ per Dexterity/g, ' 每点敏捷')
    .replace(/Orb Effects Applied to this Item are Doubled/g, '双倍神秘之球奖励')
    .replace(/ Life regenerated per second/g, ' 每秒生命恢复')
    .replace(/ Curse Length Reduction/g, ' 减少诅咒时间')
    .replace(/ to Defense per Socketed Rune/g, ' 每颗已镶嵌的符文增强防御')
    .replace(/Life Stolen per Hit/g, '击中偷取生命')
    .replace(/Mana Stolen per Hit/g, '击中偷取法力')

//装备
    .replace(/Weapons<br>/g, '武器<br>')
    .replace(/Throwing Knives/g, '飞刀')
    .replace(/Necromancer Scythes/g, '死灵法师专属镰刀')
    .replace(/Throwing Axes/g, '飞斧')
    .replace(/Amazon Spears/g, '亚马逊专属矛')
    .replace(/Paladin Spears/g, '圣骑士专属矛')
    .replace(/Paladin Clubs, Paladin Maces, Paladin Hammers/g, '圣骑士专属棍，棒，锤')
    .replace(/Spears/g, '长矛')
    .replace(/Sorceress Orbs/g, '法师单手法球')
    .replace(/Sorceress Crystal Swords/g, '扭曲之刃（法师）')
    .replace(/Sorceress Body Armor/g, '法师专属衣服')
    .replace(/Paladin Shields/g, '圣骑士专属盾')
    .replace(/Barbarian Shields/g, '野蛮人专属盾')
    .replace(/Assassin Shields/g, '刺客专属盾')
    .replace(/Necromancer Shields/g, '死灵法师专属盾')
    .replace(/Amazon Shields/g, '亚马逊专属盾')
    .replace(/Scythes/g, '镰刀')
    .replace(/Sceptres/g, '权杖')
    .replace(/Paladin Helms/g, '圣骑士专属头盔')
    .replace(/Paladin Clubs, Paladin Maces, Paladin Hammers/g, '圣骑士专属钝器')
    .replace(/Barbarian Swords/g, '野蛮人专属剑')
    .replace(/Barbarian One-Handed Axes/g, '野蛮人单手斧')
    .replace(/Barbarian Two-Handed Axes/g, '野蛮人双手斧')
    .replace(/One-Handed Swords/g, '单手剑')
    .replace(/One-Handed Axes/g, '单手斧')
    .replace(/Necromancer Wands/g, '死灵法师单手短杖')
    .replace(/Necromancer Staves/g, '死灵法师双手长杖')
    .replace(/Necromancer Daggers/g, '死灵法师专属匕首')
    .replace(/Necromancer Crossbows/g, '死灵法师专属十字弓')
    .replace(/Druid Staves/g, '德鲁伊专属法杖')
    .replace(/Druid Helms/g, '德鲁伊专属头盔')
    .replace(/Maces/g, '钉锤（棍棒顶端圆形发展 偏小）')
    .replace(/Hammers/g, '锤子（顶端为横向发展 偏大）')
    .replace(/Amazon Javelins/g, '亚马逊专属标枪')
    .replace(/Javelins/g, '标枪')
    .replace(/Barbarian Helms/g, '野蛮人头盔')
    .replace(/Staves/g, '长柄法杖')
    .replace(/Crossbows/g, '十字弓')
    .replace(/Druid Bows/g, '德鲁伊专属弓')
    .replace(/Amazon Bows/g, '亚马逊专属弓')
    .replace(/Amazon Helms/g, '亚马逊专属头盔')
    .replace(/Bows/g, '弓')
    .replace(/Daggers/g, '匕首')
    .replace(/Assassin Claws/g, '刺客爪')
    .replace(/Assassin Naginatas/g, '眉间刀（刺客）')
    .replace(/Body Armor/g, '衣服')
    .replace(/Circlets/g, '头环')
    .replace(/Shields/g, '盾牌')
    .replace(/Belts/g, '腰带')
    .replace(/Boots/g, '鞋子')
    .replace(/Helms/g, '头盔')
    .replace(/Gloves/g, '手套')



//菜单及基础单词
    .replace(/CUBE RECIPES/g, '合成公式')
    .replace(/>Cube Recipes/g, '>合成公式')
    .replace(/GEMS AND RUNES/g, '宝石和符文')
    .replace(/>Gems and Runes/g, '>宝石和符文')
    .replace(/>Base Items/g, '>基础装备')
    .replace(/BASE ITEMS/g, '基础装备')
    .replace(/>Items /g, '>物品 ')
    .replace(/>Runewords/g, '>神符之语')
    .replace(/SETS/g, '套装')
    .replace(/>Sets/g, '>套装')
    .replace(/>Tiered Uniques/g, '>品级暗金装备')
    .replace(/>Sacred Uniques/g, '>神圣暗金装备')
    .replace(/TIERED UNIQUES/g, '品级暗金装备')
    .replace(/SACRED UNIQUES/g, '神圣暗金装备')
    .replace(/>Quests/g, '>新增任务')
    .replace(/>Challenges/g, '>前期挑战')
    .replace(/>Dungeons<\/p>/g, '>Boss挑战<\/p><p>本页面挑战都在地狱难度下进行</p>')
    .replace(/>Dungeons/g, '>Boss挑战')
    .replace(/\[AMZ\]/g, '亚马逊')
    .replace(/\[ASN\]/g, '刺客')
    .replace(/\[BAR\]/g, '野蛮人')
    .replace(/\[DRU\]/g, '德鲁伊')
    .replace(/\[NEC\]/g, '死灵法师')
    .replace(/\[PAL\]/g, '圣骑士')
    .replace(/\[SOR\]/g, '法师')
    .replace(/Amazon/g, '亚马逊')
    .replace(/Assassin/g, '刺客')
    .replace(/Barbarian/g, '野蛮人')
    .replace(/Druid/g, '德鲁伊')
    .replace(/Necromancer/g, '死灵法师')
    .replace(/Paladin/g, '圣骑士')
    .replace(/Sorceress/g, '法师')
    .replace(/ Skills<br>/g, '技能<br>')
    .replace(/<p>See <a/g, '<p>点击 <a')
    .replace(/>THIS PAGE</g, '>这个页面<')
    .replace(/> for more information about /g, '> 查看更多信息关于 ')
    .replace(/Socketed /g, '孔数 ')
    .replace(/ to Mana/g, ' 法力值')
    .replace(/ Enhanced Defense/g, '增强防御')
    .replace(/ Defense/g, ' 防御值')
    .replace(/ Skill Levels/g, '技能等级')
    .replace(/Bonus /g, '加成')
    .replace(/>REQUIRED LEVEL/g, '>需求等级')
    .replace(/>DIFFICULTY/g, '>挑战难度')
    .replace(/>VERY EASY/g, '>C 级')
    .replace(/>EASY/g, '>B 级')
    .replace(/>MODERATE/g, '>A 级')
    .replace(/>HARD/g, '>S 级')
    .replace(/>VERY HARD/g, '>SS 级')
    .replace(/>EXTREME/g, '>SSS 级')
    .replace(/>IMPOSSIBLE/g, '>SSSSSSSSSSSSSS 级')
    .replace(/>LOCKDOWN/g, '>关卡锁定')
    .replace(/0 seconds/g, '0 秒')
    .replace(/ minutes/g, ' 分钟')
    .replace(/>Locations/g, '>位置')
    .replace(/>Location/g, '>位置')
    .replace(/>Lore/g, '>背景故事')
    .replace(/>Strategy/g, '>关卡特性')
    .replace(/>Reward/g, '>Uber奖励')
    .replace(/>Reagents</g, '>基础原料<')
    .replace(/>Catalysts</g, '>催化剂 Catalysts<')
    .replace(/>DISENCHANTING/g, '>分解配方')
    .replace(/Unique\/Set Weapon/g, '暗金或套装武器')
    .replace(/Unique\/Set Armour/g, '暗金或套装护甲')
    .replace(/Unique Amulet/g, '暗金项链')
    .replace(/Unique Ring/g, '暗金戒指')
    .replace(/Unique Quiver/g, '暗金箭袋')
    .replace(/Unique Jewel/g, '暗金珠宝')
    .replace(/>Weapon:/g, '>武器：')
    .replace(/>Armour:/g, '>防具：')
    .replace(/>Amulet:/g, '>项链：')
    .replace(/>Ring:/g, '>戒指：')
    .replace(/>Quiver:/g, '>箭袋：')
    .replace(/>Jewel:/g, '>珠宝：')
    .replace(/maximum sockets.</g, '最大孔数。<')
    .replace(/See \<a/g, '<a')
    .replace(/ preset shrine modifiers./g, '<span style="color:#c3841b">圣坛固定词条</span>。')
    .replace(/ random rare modifiers \(affixes\)./g, '<span style="color:#f5e83a">随机词条</span>。')
    .replace(/ and </g, ' 以及 <')

;})

();

